CREATE USER migrator WITH PASSWORD 'STRONG_PASSWORD_HERE';

CREATE DATABASE migrator
  WITH OWNER = migrator
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8'
  TEMPLATE = template0;